services:
  redis-ludo:
    image: redis:alpine
    command: ["redis-server", "/data/redis.conf"]
    volumes:
      - ./redis_data_ludo:/data
      - ./redis_ludo.conf:/data/redis.conf
    ports:
      - "127.0.0.1:6381:6379"
    restart: unless-stopped

  postgres-ludo:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ludo
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./pgdata_ludo:/var/lib/postgresql/data
    restart: unless-stopped
